apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: securitygroup
spec:
  ## must provide one of vpcIdRef or vpcId
  # vpcIdRef:
  #   name: sample-vpc
  # vpcId: name-of-my-vpc
  deletionPolicy: Delete
  forProvider:
    groupName: my-cool-securitygroup
    description: some cool description
  providerConfigRef:
    name: aws-provider
