apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: Subnetwork
metadata:
  name: subnetwork
spec:
  name: my-cool-subnetwork
  region: us-central1
  ipCidrRange: "192.168.0.0/24"
  privateIpGoogleAccess: true
  secondaryIpRanges:
    - rangeName: pods
      ipCidrRange: 10.128.0.0/20
    - rangeName: services
      ipCidrRange: 172.16.0.0/16
  ## must provide one of networkRef or network
  # networkRef:
  #   name: sample-network
  # network: projects/crossplane-playground/global/networks/sample-network
  deletionPolicy: Delete
  providerConfigRef:
    name: gcp-provider
