apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstanceClass
metadata:
  name: cloudsqlinstancemysql
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  forProvider:
    databaseVersion: MYSQL_5_6
    region: us-west2
    settings:
      tier: db-n1-standard-4
      dataDiskType: PD_SSD
      dataDiskSizeGb: 50
      ipConfiguration:
        ipv4Enabled: true
  providerConfigRef:
    name: gcp-provider
  deletionPolicy: Delete
