apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSClusterClass
metadata:
  name: akscluster
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  ## must provide one of resourceGroupName or resourceGroupNameRef
  # resourceGroupName: group-westus-1
  # resourceGroupNameRef:
  #   name: sample-rg
  location: West US 2
  version: "1.12.8"
  nodeCount: 3
  nodeVMSize: Standard_B2ms
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  # It is a bug that this field is required by Azure cluster classes; it is not
  # used. Service principal secrets for dynamically provisioned claims are
  # written to writeConnectionSecretsToNamespace.
  writeServicePrincipalTo:
    name: unused
    namespace: unused
  providerConfigRef:
    name: example
  deletionPolicy: Delete
