apiVersion: storage.azure.crossplane.io/v1alpha3
kind: AccountClass
metadata:
  name: account
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  storageAccountName: example-storage
  resourceGroupName: group-westus-1
  storageAccountSpec:
    kind: Storage
    location: West US
    sku:
      name: Standard_LRS
      tier: Standard
    tags:
      application: crossplane
  providerConfigRef:
    name: azure-provider
  deletionPolicy: Delete
