apiVersion: storage.azure.crossplane.io/v1alpha3
kind: ContainerClass
metadata:
  name: container
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  # Azure containers read their credentials from an account. We reuse the
  # providerConfigRef class field to specify which account to read.
  accountReference:
    name: account
  providerConfigRef:
    name: account
  deletionPolicy: Delete
  nameFormat: example-%s
