apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: argo-oam-network
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingConfig:
      routingMode: REGIONAL
  deletionPolicy: Delete
  providerConfigRef:
    name: gcp-provider
