apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  labels:
    provider: aws
  name: argo-west-internetgateway
spec:
  providerRef:
    name: aws-provider-west
  reclaimPolicy: Delete
  vpcIdRef:
    name: argo-west-vpc
