apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  labels:
    provider: aws
  name: argo-west-internetgateway
spec:
  providerConfigRef:
    name: aws-provider-west
  deletionPolicy: Delete
  vpcIdRef:
    name: argo-west-vpc
