apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: argo-west-eks-securitygroup
spec:
  forProvider:
    description: security group for wordpress eks
    groupName: argo-west-eks-sg
    vpcIdRef:
      name: argo-west-vpc
  providerConfigRef:
    name: aws-provider-west
  deletionPolicy: Delete
  
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: argo-west-rds-securitygroup
spec:
  forProvider:
    description: security group for wordpress rds
    groupName: argo-west-rds-sg
    ingress:
    - cidrBlocks:
      - cidrIp: 0.0.0.0/0
        description: all ips
      fromPort: 3306
      ipProtocol: tcp
      toPort: 3306
    vpcIdRef:
      name: argo-west-vpc
  providerConfigRef:
    name: aws-provider-west
  deletionPolicy: Delete

