apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  labels:
    provider: aws
  name: argo-west-vpc
spec:
  cidrBlock: 192.168.0.0/16
  enableDnsHostNames: true
  enableDnsSupport: true
  providerRef:
    name: aws-provider-west
  reclaimPolicy: Delete
