apiVersion: database.azure.crossplane.io/v1alpha3
kind: SQLServerClass
metadata:
  name: sqlserverpostgresql
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  adminLoginName: myadmin
  ## must provide one of resourceGroupName or resourceGroupNameRef
  # resourceGroupName: group-westus-1
  # resourceGroupNameRef:
  #   name: sample-rg
  location: West US
  sslEnforced: false
  version: "9.6"
  pricingTier:
    tier: Basic
    vcores: 1
    family: Gen5
  storageProfile:
    storageGB: 25
    backupRetentionDays: 7
    geoRedundantBackup: false
  providerConfigRef:
    name: azure-provider
  deletionPolicy: Delete
