apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet
spec:
  cidrBlock: 192.168.64.0/18
  ## must provide one of either vpcIdRef or vpcId
  # vpcIdRef:
  #   name: sample-vpc
  availabilityZone: us-west-2a
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
