apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: iamrolepolicyattachment
spec:
  ## must provide one of roleNameRef or roleName
  # roleNameRef:
  #   name: sample-eks-cluster-role
  # roleName: my-role
  ## wellknown policy arn
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
    roleNameRef:
      name: argo-iamrole
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider
