apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: internetgateway
spec:
  ## must provide one of vpcIdRef or vpcId
  # vpcIdRef:
  #   name: sample-vpc
  # vpcId: my-vpc
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider
