apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  labels:
    provider: aws
  name: argo-east-iamrole
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    description: iam role for wordpress eks
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete

---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  labels:
    provider: aws
  name: argo-east-cluster-iamrolepolicyattachment
spec:
  policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  forProvider:
    roleNameRef:
      name: argo-east-iamrole
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  labels:
    provider: aws
  name: argo-east-service-iamrolepolicyattachment
spec:
  policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  forProvider:
    roleNameRef:
      name: argo-east-iamrole