apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  labels:
    provider: aws
  name: argo-east-internetgateway
spec:
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  vpcIdRef:
    name: argo-east-vpc
