apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: argo-east-eks-securitygroup
spec:
  description: security group for wordpress eks
  groupName: argo-east-eks-sg
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  vpcIdRef:
    name: argo-east-vpc
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    provider: aws
  name: argo-east-rds-securitygroup
spec:
  description: security group for wordpress rds
  groupName: argo-east-rds-sg
  ingress:
  - cidrBlocks:
    - cidrIp: 0.0.0.0/0
      description: all ips
    fromPort: 3306
    protocol: tcp
    toPort: 3306
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  vpcIdRef:
    name: argo-east-vpc
