apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-east-subnet1
spec:
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 192.168.64.0/18
    vpcIdRef:
      name: argo-east-vpc
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-east-subnet2
spec:
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 192.168.128.0/18
    vpcIdRef:
      name: argo-east-vpc
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-east-subnet3
spec:
  forProvider:
    availabilityZone: us-east-1c
    cidrBlock: 192.168.192.0/18
    vpcIdRef:
      name: argo-east-vpc
  providerConfigRef:
    name: aws-provider-east
  deletionPolicy: Delete
  
