apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: Network
metadata:
  name: network
spec:
  name: my-cool-network
  autoCreateSubnetworks: false
  routingConfig:
    routingMode: REGIONAL
  deletionPolicy: Delete
  providerConfigRef:
    name: gcp-provider
