apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: routetable
spec:
  ## must provide one of vpcIdRef and vpcId
  # vpcIdRef:
  #   name: sample-vpc
  # vpcId: my-vpc
  ## routes and associations can either be assigned using names or references
  # routes:
  #   - destinationCidrBlock: 0.0.0.0/0
  #     gatewayIdRef:
  #       name: sample-internetgateway
  # associations:
  #   - subnetIdRef:
  #       name: sample-subnet1
  #   - subnetIdRef:
  #       name: sample-subnet2
  #   - subnetIdRef:
  #       name: sample-subnet3
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider
