apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: BucketClass
metadata:
  name: bucket
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: gcp-provider
  deletionPolicy: Delete
